[package]
name = "archividian"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive", "string"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
